version: '3.1'

services:
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'todo'
